FROM node:15 as build-stage
WORKDIR /app
COPY package*.json /app/
COPY .build/nginx.conf /nginx.conf
RUN npm install
COPY ./ /app/
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=build-stage /app/out/ /usr/share/nginx/html
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
